// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Person
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject personMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Person";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FirstName("FirstName"),
		LastName("LastName"),
		Address1("Address1"),
		Address2("Address2"),
		City("City"),
		State("State"),
		PostalCode("PostalCode"),
		Telephone1("Telephone1"),
		isDeleted("isDeleted"),
		DeletedTime("DeletedTime");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Person(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Person"));
	}

	protected Person(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject personMendixObject)
	{
		if (personMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Person", personMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Person");

		this.personMendixObject = personMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Person.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Person initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Person.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Person initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Person(context, mendixObject);
	}

	public static myfirstmodule.proxies.Person load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Person.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Person> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Person> result = new java.util.ArrayList<myfirstmodule.proxies.Person>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Person" + xpathConstraint))
			result.add(myfirstmodule.proxies.Person.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of Address1
	 */
	public final java.lang.String getAddress1()
	{
		return getAddress1(getContext());
	}

	/**
	 * @param context
	 * @return value of Address1
	 */
	public final java.lang.String getAddress1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address1.toString());
	}

	/**
	 * Set value of Address1
	 * @param address1
	 */
	public final void setAddress1(java.lang.String address1)
	{
		setAddress1(getContext(), address1);
	}

	/**
	 * Set value of Address1
	 * @param context
	 * @param address1
	 */
	public final void setAddress1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address1)
	{
		getMendixObject().setValue(context, MemberNames.Address1.toString(), address1);
	}

	/**
	 * @return value of Address2
	 */
	public final java.lang.String getAddress2()
	{
		return getAddress2(getContext());
	}

	/**
	 * @param context
	 * @return value of Address2
	 */
	public final java.lang.String getAddress2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address2.toString());
	}

	/**
	 * Set value of Address2
	 * @param address2
	 */
	public final void setAddress2(java.lang.String address2)
	{
		setAddress2(getContext(), address2);
	}

	/**
	 * Set value of Address2
	 * @param context
	 * @param address2
	 */
	public final void setAddress2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address2)
	{
		getMendixObject().setValue(context, MemberNames.Address2.toString(), address2);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode()
	{
		return getPostalCode(getContext());
	}

	/**
	 * @param context
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PostalCode.toString());
	}

	/**
	 * Set value of PostalCode
	 * @param postalcode
	 */
	public final void setPostalCode(java.lang.String postalcode)
	{
		setPostalCode(getContext(), postalcode);
	}

	/**
	 * Set value of PostalCode
	 * @param context
	 * @param postalcode
	 */
	public final void setPostalCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postalcode)
	{
		getMendixObject().setValue(context, MemberNames.PostalCode.toString(), postalcode);
	}

	/**
	 * @return value of Telephone1
	 */
	public final java.lang.String getTelephone1()
	{
		return getTelephone1(getContext());
	}

	/**
	 * @param context
	 * @return value of Telephone1
	 */
	public final java.lang.String getTelephone1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Telephone1.toString());
	}

	/**
	 * Set value of Telephone1
	 * @param telephone1
	 */
	public final void setTelephone1(java.lang.String telephone1)
	{
		setTelephone1(getContext(), telephone1);
	}

	/**
	 * Set value of Telephone1
	 * @param context
	 * @param telephone1
	 */
	public final void setTelephone1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String telephone1)
	{
		getMendixObject().setValue(context, MemberNames.Telephone1.toString(), telephone1);
	}

	/**
	 * @return value of isDeleted
	 */
	public final java.lang.Boolean getisDeleted()
	{
		return getisDeleted(getContext());
	}

	/**
	 * @param context
	 * @return value of isDeleted
	 */
	public final java.lang.Boolean getisDeleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isDeleted.toString());
	}

	/**
	 * Set value of isDeleted
	 * @param isdeleted
	 */
	public final void setisDeleted(java.lang.Boolean isdeleted)
	{
		setisDeleted(getContext(), isdeleted);
	}

	/**
	 * Set value of isDeleted
	 * @param context
	 * @param isdeleted
	 */
	public final void setisDeleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdeleted)
	{
		getMendixObject().setValue(context, MemberNames.isDeleted.toString(), isdeleted);
	}

	/**
	 * @return value of DeletedTime
	 */
	public final java.util.Date getDeletedTime()
	{
		return getDeletedTime(getContext());
	}

	/**
	 * @param context
	 * @return value of DeletedTime
	 */
	public final java.util.Date getDeletedTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DeletedTime.toString());
	}

	/**
	 * Set value of DeletedTime
	 * @param deletedtime
	 */
	public final void setDeletedTime(java.util.Date deletedtime)
	{
		setDeletedTime(getContext(), deletedtime);
	}

	/**
	 * Set value of DeletedTime
	 * @param context
	 * @param deletedtime
	 */
	public final void setDeletedTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date deletedtime)
	{
		getMendixObject().setValue(context, MemberNames.DeletedTime.toString(), deletedtime);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return personMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Person that = (myfirstmodule.proxies.Person) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Person";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
